# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


  config.vm.box = "debian/buster64"

  
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

 
  config.vm.network "private_network", ip: "192.168.33.10"

 

  
  
  config.vm.provision "shell", inline: <<-SHELL
    
	sudo apt install -y apache2
     	sudo chmod 775 /var/www/html
     	sudo chown -R root:vagrant /var/www/html
     	sudo cp /vagrant/index.html /var/www/html
	sudo cp /vagrant/index.php /var/www/html
    	sudo systemctl enable apache2
     	sudo systemctl start apache2

	sudo apt install -y php libapache2-mod-php

	sudo systemctl restart apache2




  SHELL
end
