# -*- mode: ruby -*-
# vi: set ft=ruby :
# M Gasilov


Vagrant.configure("2") do |config|


  config.vm.box = "centos/8"

  
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

 
  config.vm.network "private_network", ip: "192.168.33.10"

 

  
  
  config.vm.provision "shell", inline: <<-SHELL
    
	sudo yum update
	sudo yum install mysql-server
	sudo systemctl start mysqld
	sudo yum install httpd
     	sudo chmod 775 /var/www/html
     	sudo chown -R root:vagrant /var/www/html
     	sudo cp /vagrant/index.html /var/www/html
	sudo cp /vagrant/index.php /var/www/html
	systemctl enable httpd
	sudo systemctl start httpd
	sudo yum install php
	sudo systemctl restart httpd

  SHELL
end
